### ISSUE TITLE
upgrade travis ci to node 4

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#25]
```
env:
  - CXX="g++-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
node_js:
  - 4.1.0
```

Should check if all that stuff is still necessary and if we need to specify the entire version (maybe - 4 just works for all 4.x versions)
